language: node_js
node_js: node
services:
- mongodb
env: 
- NODE_ENV=test
-DB_URL=mongodb://root:root@ds115701.mlab.com:15701/apollotest
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'